apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
        - name: app-2
          image: ghcr.io/denoslab/ensf400-sample-app:v2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-2-svc
spec:
  selector:
    app: app-2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
